LOP and Unoswap bugs
duneanalytics/dune-v1-abstractions pull request #2
Opened 2022-12-14 20:32 UTC by jacubcub

just copying [PR 2117 from spellbook repo](https://github.com/duneanalytics/spellbook/pull/2117) by @fatayri to this new repository

2022-12-14 21:37 UTC, dot2dotseurat commented
@jacubcub thank you! I'm adding @jeff-dude and @masquot back as the reviewers as they will be the ones to deploy this. I appreciate the flexibility.

2022-12-15 10:23 UTC, masquot requested changes
@fatayri - probably a few small fixes will help us bring this one over the finishing line

2022-12-15 10:23 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +                from oneinch."AggregationRouterV5_call_unoswap_withPermit"
A contract with this name does not exist in the database. Did you mean?

oneinch."AggregationRouterV5_call_unoswapToWithPermit"

![Screenshot 2022-12-15 at 10 57 44](https://user-images.githubusercontent.com/78954627/207833427-53a3a7cb-8c88-4422-b79e-38f830180300.png)

2022-12-15 10:23 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            t."from" AS trader_a,
the traces table using alias `t` is not accessible in this outer statement. But `trader_a` is already defined on line 360, so we can probably just reference that here?

2022-12-15 10:23 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            (CASE WHEN ll.to = '\xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' AND substring("pools"[ARRAY_LENGTH("pools", 1)] from 1 for 1) IN ('\xc0', '\x40') THEN '\xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
runtime error: 
> Error: Missing FROM-clause entry for table "ll" at line 11, position 24.

2022-12-15 10:25 UTC, masquot commented on deprecated-dune-v1-abstractions/ethereum/dex/trades/insert_1inch.sql
> +            (CASE WHEN ll.to = '\xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' AND substring("pools"[ARRAY_LENGTH("pools", 1)] from 1 for 1) IN ('\xc0', '\x40') THEN '\xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
See also here: https://dune.com/queries/1761805

2022-12-15 10:31 UTC, fatayri commented
damn, sorry, writing this PR on a hectic day without being able to properly test didn't help much.

will fix now

2022-12-15 10:48 UTC, fatayri commented
@masquot Fixed it here: https://dune.com/queries/1762081 

Do you want me to create a separate PR (as this one is technically not mine) or it's fine?

2022-12-15 11:17 UTC, masquot commented
Thank you @fatayri. Let me have a look. I don't think new PR will be needed.

2022-12-15 13:22 UTC, masquot commented
@dot2dotseurat - could you grant me rights for this repo so I can add commits to this PR directly?

@fatayri - Started writing code to DB based on the query you linked.

2022-12-15 13:46 UTC, bh2smith commented
Looks like some of the 1inch data is "back online" although there is still a gap between december 1 and 2 days ago (1inch is PINK)

![Screenshot 2022-12-15 at 14 45 48](https://user-images.githubusercontent.com/11778116/207874754-91190d9d-d5b0-4ce0-8eaf-dc70e0262769.png)

2022-12-15 14:26 UTC, masquot commented
> Looks like some of the 1inch data is "back online" although there is still a gap between december 1 and 2 days ago (1inch is PINK)
> 
> ![Screenshot 2022-12-15 at 14 45 48](https://user-images.githubusercontent.com/11778116/207874754-91190d9d-d5b0-4ce0-8eaf-dc70e0262769.png)

Thank you @bh2smith. I wrote (partial) data to Postgres for the 15th by way of test earlier. The backfill for the full month of December has started, but is progressing extremely slowly.

Would be really great to port this code over to v2.

2022-12-15 14:42 UTC, bh2smith commented
> Would be really great to port this code over to v2.

💯 - couldn't agree more!

2022-12-15 15:12 UTC, jacubcub commented
> Would be really great to port this code over to v2.
Agree and something I plan on working on next couple months. Started here a while back, maybe some of it is still useful https://github.com/duneanalytics/spellbook/pull/1398

@fatayri sorry to steal your PR, just really need dex.trades back up

2022-12-15 15:26 UTC, bh2smith commented
> just really need dex.trades back up

Ditto!

2022-12-16 15:04 UTC, fleupold commented
> The backfill for the full month of December has started, but is progressing extremely slowly.

@masquot could you please check on the progress? It's been 24h and it seems the data hasn't caught up yet.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1200333/208126996-8cdf3419-ce4e-4fc6-aac6-9ac624877f02.png">

2022-12-18 13:14 UTC, masquot commented
Thank you @fleupold. I had to run the job in daily increments to get it to finish, and, you are right, these incremental jobs ran for multiple days.

Does the data look fine again from your perspective?

2022-12-18 14:00 UTC, bh2smith commented
Looks all good now based on this - https://dune.com/queries/328103

<img width="1142" alt="Screenshot 2022-12-18 at 14 59 44" src="https://user-images.githubusercontent.com/11778116/208302525-c42a7872-f91b-4b21-8b5f-6576a7aa7e75.png">

2022-12-19 15:15 UTC, masquot approved these changes

2022-12-19 15:15 UTC, merged